version: '3.4'

services:
  apinotblet:
    image: ${DOCKER_REGISTRY-}apinotblet
    ports:
      - "9090:8080"
      - "9091:8081"
    build:
      context: .
      dockerfile: ApiNotblet/Dockerfile


